let img=document.getElementById("iits-img");
img.src="https://mediaproxy.salon.com/width/1200/https://media.salon.com/1999/11/pokimon_the_first_movie.jpg"
let ma=document.getElementById("iits-email");
ma.src="mailto:rubyiarabonti@gmail.com";
let fb=document.getElementById("iits-fb-link");
fb.src="https://www.facebook.com/profile.php?id=100056517896174&mibextid=ZbWKwL";
let git=document.getElementById("iits-github-link");
git.src="rubyiashaiyara";
let ci=document.getElementById("iits-bg");
ci.classList.remove("bg-danger");
ci.classList.add("bg-primary");
let bt=document.getElementById("iits-btn");
bt.classList.remove("bg-danger");
bt.classList.add("bg-primary");
let w=document.getElementById("iits-name");
w.classList.remove("text-danger");
w.classList.add("text-primary");
let cp=document.getElementById("iits-cr-msg");
cp.textContent="hi i am Rubyia";
let mn=document.getElementById("iits-name");
mn.textContent="Rubyia Shaiyara";
mn.classList.remove("text-danger");
mn.classList.add("text-primary")
let up=document.getElementById("iits-prof");
up.classList.remove("text-danger");
up.classList.add("text-primary")
up.textContent="Student";
let edu=document.getElementById("iits-edu");
edu.classList.remove("text-danger");
edu.classList.add("text-primary");
edu.textContent="5th symister";
let fs=document.getElementById("iits-study");
fs.classList.remove("text-danger");
fs.classList.add("text-primary");
fs.textContent="CSE";
let sc=document.getElementById("iits-school");
sc.classList.remove("text-danger");
sc.classList.add("text-Primary")
sc.textContent="IUBAT";
let int=document.getElementById("iits-passion");
int.classList.remove("text-danger");
int.classList.add("text-primary");
int.textContent="coding";
let ny=document.getElementById("iits-numYears");
ny.classList.remove("text-danger");
ny.classList.add("text-primary");
ny.textContent="8n mounth";
let hb=document.getElementById("iits-hobby");
hb.classList.remove("text-danger");
hb.classList.add("text-primary");
hb.textContent="Cooking";
let crc =document.getElementById("iits-crc");
crc.classList.remove("text-danger");
crc.classList.add("text-primary");
crc.textContent="like gardening";
let ab =document.getElementById("iits-ability");
ab.classList.remove("text-danger");
ab.classList.add("text-primary");
ab.textContent="i am not good all time but i dont fotget about trying";
let ig =document.getElementById("iits-goal");
ig.classList.remove("text-danger");
ig.classList.add("text-primary");
ig.textContent="want to be a independent woman";